// Country calling codes (ITU E.164 allocations), with ISO 3166-1 alpha-2
// codes so we can render a flag emoji and search by name or code.
// Grouped by region for readability; order within the exported array
// doesn't matter since consumers sort/filter as needed.
export const COUNTRY_CODES = [
  // Africa
  { code: "213", iso2: "DZ", name: "Algeria" },
  { code: "244", iso2: "AO", name: "Angola" },
  { code: "229", iso2: "BJ", name: "Benin" },
  { code: "267", iso2: "BW", name: "Botswana" },
  { code: "226", iso2: "BF", name: "Burkina Faso" },
  { code: "257", iso2: "BI", name: "Burundi" },
  { code: "238", iso2: "CV", name: "Cabo Verde" },
  { code: "237", iso2: "CM", name: "Cameroon" },
  { code: "236", iso2: "CF", name: "Central African Republic" },
  { code: "235", iso2: "TD", name: "Chad" },
  { code: "269", iso2: "KM", name: "Comoros" },
  { code: "242", iso2: "CG", name: "Congo-Brazzaville" },
  { code: "243", iso2: "CD", name: "Congo-Kinshasa (DRC)" },
  { code: "253", iso2: "DJ", name: "Djibouti" },
  { code: "20", iso2: "EG", name: "Egypt" },
  { code: "240", iso2: "GQ", name: "Equatorial Guinea" },
  { code: "291", iso2: "ER", name: "Eritrea" },
  { code: "268", iso2: "SZ", name: "Eswatini" },
  { code: "251", iso2: "ET", name: "Ethiopia" },
  { code: "241", iso2: "GA", name: "Gabon" },
  { code: "220", iso2: "GM", name: "Gambia" },
  { code: "233", iso2: "GH", name: "Ghana" },
  { code: "224", iso2: "GN", name: "Guinea" },
  { code: "245", iso2: "GW", name: "Guinea-Bissau" },
  { code: "225", iso2: "CI", name: "Ivory Coast" },
  { code: "254", iso2: "KE", name: "Kenya" },
  { code: "266", iso2: "LS", name: "Lesotho" },
  { code: "231", iso2: "LR", name: "Liberia" },
  { code: "218", iso2: "LY", name: "Libya" },
  { code: "261", iso2: "MG", name: "Madagascar" },
  { code: "265", iso2: "MW", name: "Malawi" },
  { code: "223", iso2: "ML", name: "Mali" },
  { code: "222", iso2: "MR", name: "Mauritania" },
  { code: "230", iso2: "MU", name: "Mauritius" },
  { code: "212", iso2: "MA", name: "Morocco" },
  { code: "258", iso2: "MZ", name: "Mozambique" },
  { code: "264", iso2: "NA", name: "Namibia" },
  { code: "227", iso2: "NE", name: "Niger" },
  { code: "234", iso2: "NG", name: "Nigeria" },
  { code: "250", iso2: "RW", name: "Rwanda" },
  { code: "239", iso2: "ST", name: "Sao Tome and Principe" },
  { code: "221", iso2: "SN", name: "Senegal" },
  { code: "248", iso2: "SC", name: "Seychelles" },
  { code: "232", iso2: "SL", name: "Sierra Leone" },
  { code: "252", iso2: "SO", name: "Somalia" },
  { code: "27", iso2: "ZA", name: "South Africa" },
  { code: "211", iso2: "SS", name: "South Sudan" },
  { code: "249", iso2: "SD", name: "Sudan" },
  { code: "255", iso2: "TZ", name: "Tanzania" },
  { code: "228", iso2: "TG", name: "Togo" },
  { code: "216", iso2: "TN", name: "Tunisia" },
  { code: "256", iso2: "UG", name: "Uganda" },
  { code: "260", iso2: "ZM", name: "Zambia" },
  { code: "263", iso2: "ZW", name: "Zimbabwe" },

  // Middle East
  { code: "973", iso2: "BH", name: "Bahrain" },
  { code: "98", iso2: "IR", name: "Iran" },
  { code: "964", iso2: "IQ", name: "Iraq" },
  { code: "972", iso2: "IL", name: "Israel" },
  { code: "962", iso2: "JO", name: "Jordan" },
  { code: "965", iso2: "KW", name: "Kuwait" },
  { code: "961", iso2: "LB", name: "Lebanon" },
  { code: "968", iso2: "OM", name: "Oman" },
  { code: "970", iso2: "PS", name: "Palestine" },
  { code: "974", iso2: "QA", name: "Qatar" },
  { code: "966", iso2: "SA", name: "Saudi Arabia" },
  { code: "963", iso2: "SY", name: "Syria" },
  { code: "971", iso2: "AE", name: "United Arab Emirates" },
  { code: "967", iso2: "YE", name: "Yemen" },

  // Asia
  { code: "93", iso2: "AF", name: "Afghanistan" },
  { code: "374", iso2: "AM", name: "Armenia" },
  { code: "994", iso2: "AZ", name: "Azerbaijan" },
  { code: "880", iso2: "BD", name: "Bangladesh" },
  { code: "975", iso2: "BT", name: "Bhutan" },
  { code: "673", iso2: "BN", name: "Brunei" },
  { code: "855", iso2: "KH", name: "Cambodia" },
  { code: "86", iso2: "CN", name: "China" },
  { code: "995", iso2: "GE", name: "Georgia" },
  { code: "852", iso2: "HK", name: "Hong Kong" },
  { code: "91", iso2: "IN", name: "India" },
  { code: "62", iso2: "ID", name: "Indonesia" },
  { code: "81", iso2: "JP", name: "Japan" },
  { code: "7", iso2: "KZ", name: "Kazakhstan" },
  { code: "850", iso2: "KP", name: "North Korea" },
  { code: "82", iso2: "KR", name: "South Korea" },
  { code: "996", iso2: "KG", name: "Kyrgyzstan" },
  { code: "856", iso2: "LA", name: "Laos" },
  { code: "853", iso2: "MO", name: "Macau" },
  { code: "60", iso2: "MY", name: "Malaysia" },
  { code: "960", iso2: "MV", name: "Maldives" },
  { code: "976", iso2: "MN", name: "Mongolia" },
  { code: "95", iso2: "MM", name: "Myanmar" },
  { code: "977", iso2: "NP", name: "Nepal" },
  { code: "92", iso2: "PK", name: "Pakistan" },
  { code: "63", iso2: "PH", name: "Philippines" },
  { code: "65", iso2: "SG", name: "Singapore" },
  { code: "94", iso2: "LK", name: "Sri Lanka" },
  { code: "886", iso2: "TW", name: "Taiwan" },
  { code: "992", iso2: "TJ", name: "Tajikistan" },
  { code: "66", iso2: "TH", name: "Thailand" },
  { code: "670", iso2: "TL", name: "Timor-Leste" },
  { code: "993", iso2: "TM", name: "Turkmenistan" },
  { code: "998", iso2: "UZ", name: "Uzbekistan" },
  { code: "84", iso2: "VN", name: "Vietnam" },
  { code: "357", iso2: "CY", name: "Cyprus" },

  // Europe
  { code: "355", iso2: "AL", name: "Albania" },
  { code: "376", iso2: "AD", name: "Andorra" },
  { code: "43", iso2: "AT", name: "Austria" },
  { code: "375", iso2: "BY", name: "Belarus" },
  { code: "32", iso2: "BE", name: "Belgium" },
  { code: "387", iso2: "BA", name: "Bosnia and Herzegovina" },
  { code: "359", iso2: "BG", name: "Bulgaria" },
  { code: "385", iso2: "HR", name: "Croatia" },
  { code: "420", iso2: "CZ", name: "Czechia" },
  { code: "45", iso2: "DK", name: "Denmark" },
  { code: "372", iso2: "EE", name: "Estonia" },
  { code: "358", iso2: "FI", name: "Finland" },
  { code: "33", iso2: "FR", name: "France" },
  { code: "49", iso2: "DE", name: "Germany" },
  { code: "30", iso2: "GR", name: "Greece" },
  { code: "36", iso2: "HU", name: "Hungary" },
  { code: "354", iso2: "IS", name: "Iceland" },
  { code: "353", iso2: "IE", name: "Ireland" },
  { code: "39", iso2: "IT", name: "Italy" },
  { code: "383", iso2: "XK", name: "Kosovo" },
  { code: "371", iso2: "LV", name: "Latvia" },
  { code: "423", iso2: "LI", name: "Liechtenstein" },
  { code: "370", iso2: "LT", name: "Lithuania" },
  { code: "352", iso2: "LU", name: "Luxembourg" },
  { code: "356", iso2: "MT", name: "Malta" },
  { code: "373", iso2: "MD", name: "Moldova" },
  { code: "377", iso2: "MC", name: "Monaco" },
  { code: "382", iso2: "ME", name: "Montenegro" },
  { code: "31", iso2: "NL", name: "Netherlands" },
  { code: "389", iso2: "MK", name: "North Macedonia" },
  { code: "47", iso2: "NO", name: "Norway" },
  { code: "48", iso2: "PL", name: "Poland" },
  { code: "351", iso2: "PT", name: "Portugal" },
  { code: "40", iso2: "RO", name: "Romania" },
  { code: "7", iso2: "RU", name: "Russia" },
  { code: "378", iso2: "SM", name: "San Marino" },
  { code: "381", iso2: "RS", name: "Serbia" },
  { code: "421", iso2: "SK", name: "Slovakia" },
  { code: "386", iso2: "SI", name: "Slovenia" },
  { code: "34", iso2: "ES", name: "Spain" },
  { code: "46", iso2: "SE", name: "Sweden" },
  { code: "41", iso2: "CH", name: "Switzerland" },
  { code: "90", iso2: "TR", name: "Turkey" },
  { code: "380", iso2: "UA", name: "Ukraine" },
  { code: "44", iso2: "GB", name: "United Kingdom" },
  { code: "379", iso2: "VA", name: "Vatican City" },

  // Americas
  { code: "1", iso2: "US", name: "United States" },
  { code: "1", iso2: "CA", name: "Canada" },
  { code: "54", iso2: "AR", name: "Argentina" },
  { code: "1", iso2: "BS", name: "Bahamas" },
  { code: "1", iso2: "BB", name: "Barbados" },
  { code: "501", iso2: "BZ", name: "Belize" },
  { code: "591", iso2: "BO", name: "Bolivia" },
  { code: "55", iso2: "BR", name: "Brazil" },
  { code: "56", iso2: "CL", name: "Chile" },
  { code: "57", iso2: "CO", name: "Colombia" },
  { code: "506", iso2: "CR", name: "Costa Rica" },
  { code: "53", iso2: "CU", name: "Cuba" },
  { code: "1", iso2: "DO", name: "Dominican Republic" },
  { code: "593", iso2: "EC", name: "Ecuador" },
  { code: "503", iso2: "SV", name: "El Salvador" },
  { code: "502", iso2: "GT", name: "Guatemala" },
  { code: "592", iso2: "GY", name: "Guyana" },
  { code: "509", iso2: "HT", name: "Haiti" },
  { code: "504", iso2: "HN", name: "Honduras" },
  { code: "1", iso2: "JM", name: "Jamaica" },
  { code: "52", iso2: "MX", name: "Mexico" },
  { code: "505", iso2: "NI", name: "Nicaragua" },
  { code: "507", iso2: "PA", name: "Panama" },
  { code: "595", iso2: "PY", name: "Paraguay" },
  { code: "51", iso2: "PE", name: "Peru" },
  { code: "1", iso2: "TT", name: "Trinidad and Tobago" },
  { code: "598", iso2: "UY", name: "Uruguay" },
  { code: "58", iso2: "VE", name: "Venezuela" },

  // Oceania
  { code: "61", iso2: "AU", name: "Australia" },
  { code: "679", iso2: "FJ", name: "Fiji" },
  { code: "64", iso2: "NZ", name: "New Zealand" },
  { code: "675", iso2: "PG", name: "Papua New Guinea" },
  { code: "685", iso2: "WS", name: "Samoa" },
  { code: "677", iso2: "SB", name: "Solomon Islands" },
  { code: "676", iso2: "TO", name: "Tonga" },
  { code: "678", iso2: "VU", name: "Vanuatu" },
];

// Longest codes first, so auto-detect / prefix matching tries "880" before
// it could mis-match a shorter, unrelated prefix like "8".
export const CODES_BY_LENGTH_DESC = [...COUNTRY_CODES].sort(
  (a, b) => b.code.length - a.code.length
);

// Convert an ISO 3166-1 alpha-2 code ("BD") into its flag emoji (🇧🇩)
// using regional indicator symbols — no need to hand-maintain 150+ emoji.
export function flagEmoji(iso2) {
  if (!iso2 || iso2.length !== 2) return "🏳️";
  return String.fromCodePoint(
    ...[...iso2.toUpperCase()].map((c) => 127397 + c.charCodeAt(0))
  );
}
